### PR TITLE
Multi-tile-output

### PR DESCRIPTION
**Pull request by fraserwg**
This pull request should enable the opening of tiled MITgcm MDS datasets (see issue #28). The implementation does not use zarr as suggested in the comments of this issue, but should enable users to open tiled datasets, using a dask backend, in a similar manner to how untiled datasets are.

### CODE REVIEW

**Comment by fraserwg** [comment]
I think this is failing because the tests can't find the new `tiled_gyre.tar.gz` file I've added in the `xmitgcm/test` folder, but I'm not too sure how to fix this.

**Comment by rabernat** [comment]
@fraserwg - thanks so much for getting this started! 🎉 

> I think this is failing because the tests can't find the new `tiled_gyre.tar.gz` file I've added in the `xmitgcm/test` folde

We should definitely not be keeping large binary files in the github repo. The test data currently live in figshare: https://figshare.com/collections/xmitgcm_test_data/4362224

I have downloaded the file and will upload it there. In the meantime, you should remove the file from this PR. Note that itn't enough to to `git rm`, since the file will stay in the git history. You need to actually [remove it from the history](https://www.deployhq.com/git/faqs/removing-large-files-from-git-history). Sorry that this was not made clear earlier.

**Comment by fraserwg** [comment]
I tried to remove the file from the history but now it looks like every single commit ever made to the repository is listed in this pull request. Apologies if this has broken anything!

**Comment by rabernat** [comment]
Hi @fraserwg -- I'm really sorry that your first PR to xmitgcm involves such a git mess. I know this must feel very frustrating.

Here is my recommendation for how to resolve it:
- Copy all of the code files that you have actually changed to implement this new feature into a temporary directory
- Check out a fresh, clean copy of the repo
- Cop the files from the temporary directory to the fresh clean repo
- Add and commit those files (do not add the .gz file)
- Close this PR and open a new one from that clean copy

I thank your contribution and your patience. I will post the obligatory [xkcd cartoon about git](https://xkcd.com/1597/).

xkcd cartoon

**Comment by fraserwg** [comment]
Hahah -- it's no problem. Another pull request should be incoming shortly.

**Comment by AaronDavidSchneider** [comment]
Hi @fraserwg and @rabernat, followed the discussion here and in #28 and am now curious if people continued to work on the issue? I could not find any PR that fixes the git related issues in this PR.

**Comment by fraserwg** [comment]
From what I remember (having not touched this for a while) this branch, although not merged,  should read the tiled datasets in ok. You should be able to call `xmitgcm.open_mdsdataset` as usual, but with the keyword option `tiled=True` if you install xmitgcm using this branch.

**Comment by fraserwg** [comment]
Actually, I think PR #290 is the one you want to install from, as that doesn't have the "git mess" mentioned earlier in this thread. Tiled datasets are read in in the same way though.

**Comment by AaronDavidSchneider** [comment]
Thanks for the message. Is this PR ready to go? Is it just the tests that need to be fixed? If it's already close to being ready, I could pick it up.

**Comment by fraserwg** [comment]
I think it is ready to go, but the tiled test data isn't in the test data store so it won't pass all tests atm. I'm also not too sure how well the code scales (for larger tiled domains) so I'd suggest trying it and seeing if it works for you. If it's slow you may want to fork the branch and have a go at refactoring things for performance.

**Pull request closed without merging**
