### PR TITLE
Python 3.8 compatibility

### PR DESCRIPTION
**Pull request by roxyboy**
Updated some functions that had deprecation warnings.

### CODE REVIEW

**Comment by roxyboy** [comment]
The tests all pass in Python 3.6-3.8 but fails in Python 2.7 due to the function `dask.drop_var()` not being supported. How do you think about dropping support for Python 2.7 @rabernat ??

**Comment by rabernat** [comment]
I think we can drop python 2 in future releases. Thanks for this!

**Comment by roxyboy** [comment]
Ok, all tests in py27 and py3 pass now :)

**Comment by rabernat** [comment]
I guess this will also fix the annoying deprecations warnings from xarray.auto_combine. Great work Takaya!

**Pull request merged**
